// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RemoveWatcher(arg1) {
  return window['go']['main']['App']['RemoveWatcher'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
