// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function RemoveWatcher(arg1:string):Promise<main.Result>;

export function SelectFile():Promise<main.Result>;
